added html and necessary files
God-Logic/Code-Review-Project pull request #1
Opened 2023-02-28 16:20 UTC by God-Logic

Reviewing my changes

2023-02-28 16:28 UTC, God-Logic commented on initial.html
> +  <section id = "features">
Please use class instead of Id. The id should be used only on specific identification and can only be used once. Class is reusable.

2023-02-28 16:30 UTC, God-Logic commented on .hintrc
> +{
I suggest that instead of using initial.html, use Index.html

2023-02-28 16:31 UTC, God-Logic commented on .hintrc
> +  "connector": {
May you please use style.css instead of styles.css.

2023-02-28 16:46 UTC, souad988 commented on initial.html
> +  <section id = "features">
Very well done by adding this inline comment in the correct line you mention issue about 💪 also your comment is polite explaining reason why the change is requested and suggesting an alternative 🎯💪✔

2023-02-28 16:52 UTC, souad988 commented on .hintrc
> +{
unlike the first comment this one is not placed in the correct line or block of code , also please include an argument why the change is requested

2023-02-28 17:42 UTC, souad988 requested changes
Hi @God-Logic , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![212385281-4797c58a-d358-423a-aa7c-832c22203865](https://user-images.githubusercontent.com/59707859/221933816-031f9279-6741-41eb-b16e-add351042daf.gif)


## Highlights
✔Use inline comments
✔Good use of github workflow


## Required Changes ♻️
_Check the comments under the review._
_Also kindly highlight some good part of the word that the student have done correctly as this encourage them to keep working.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 17:42 UTC, souad988 commented on initial.html
> +  <section id = "features">
Very well done by adding this inline comment in the correct line you mention issue about 💪 also your comment is polite explaining reason why the change is requested and suggesting an alternative 🎯💪✔

2023-03-01 00:33 UTC, God-Logic reviewed
You are almost there. Make the changes pointed out and you are good to go.

2023-03-01 00:33 UTC, God-Logic commented on initial.html
> +    <div id="head-logo">
Hey, good work so far. You made sure that the h1 element appears only once in this project👌 and followed the structure of HTML, separating all different sections and putting divs inside them✨✨✨. I suggest that for the sake of being able to reuse an identifier, instead of using an Id use a class. Classes can be reused, unlike Id which can only be applied once.👍

2023-03-01 00:33 UTC, God-Logic commented on initial.html
> +  <div>
Weldone putting the right type of list inside a dive, that is inside a section ✨🎉. I kindly suggest that instead of opening multiple divs, try putting all the <h3>, <ol>, and <li> elements in one div. This way you have more control over the elements since they are very similar, Opening a single class in the div will allow you to add CSS to everything at once.

2023-03-01 00:50 UTC, God-Logic reviewed
You are almost there, please revisit the comments and make the necessary changes. All the best.

2023-03-01 00:50 UTC, God-Logic commented on initial.html
> +    </ol>
Weldone putting the right types of list inside a dive, that is inside a section ✨🎉. I kindly suggest that instead of opening multiple divs, try putting all the  h3, ordered list, and list elements in one div. This way you have more control over the elements since they are very similar, Opening a single class in the div will allow you to add CSS to everything at once.

2023-03-01 00:50 UTC, God-Logic commented on initial.html
> +    </ol>
This is a proper use of HTML, you deserve a star for that✔✨✨. Kindly add the necessary information inside the h3 element and the list element. Nothing will be displayed if you put nothing in those.

2023-03-01 01:05 UTC, Shedrack-Sunday approved these changes
Hi @God-Logic 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

__check the comments for details

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-01 01:05 UTC, Shedrack-Sunday commented on initial.html
> +    <div id="head-logo">
- [Optional] Instead of writing bare h1, consider making all tags highlighted by using back string back and front to give `h1` for example 👍

2023-03-01 01:05 UTC, Shedrack-Sunday commented on initial.html
> +    </ol>
- [Optional] Here also, Instead of writing bare h1, div consider making all tags highlighted by using back string back and front to give `h1` , `div` for example 👏

2023-03-01 01:09 UTC, God-Logic commented
hey, how do I make those highlighted?

2023-03-01 01:09 UTC, merged